### ISSUE TITLE
单例toast 怎么解决android8.0以上has already been added to the window manager的问题呢

### ISSUE THREAD

**Issue by axkza** [the-pig-of-jungle/smart-show#22]
Fatal Exception: java.lang.IllegalStateException: View android.widget.LinearLayout{53bc9d9 V.E...... ......ID 0,0-135,85} has already been added to the window manager.
       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:328)
       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
       at android.widget.Toast$TN.handleShow(Toast.java:520)
       at android.widget.Toast$TN$1.handleMessage(Toast.java:424)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:192)
       at android.app.ActivityThread.main(ActivityThread.java:6792)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)

**Comment by the-pig-of-jungle** [comment]
是最新版么？是否必现？

**Comment by GeekTR** [comment]
+1
红米6 8.0必现

**Comment by GeekTR** [comment]
使用的最新版

**Comment by the-pig-of-jungle** [comment]
方便加个微信么？我做了修复，因为没有红米手机，所以需要你验证下。或者你加交流群也可以。
![微信图片_20190505114734](https://user-images.githubusercontent.com/22428959/57188106-a5f3b580-6f2b-11e9-8ed9-22acedad0461.jpg)

**Comment by the-pig-of-jungle** [comment]
先用2.7.4版本看看是否还存在该问题，有的话，微信进一步交流

**Comment by axkza** [comment]
> 使用的最新版

这个兄弟有必现的手机吗？我这里复现不了，能帮忙测试一下吗

**Comment by the-pig-of-jungle** [comment]
大家扫微信交流群，一起解决问题

**Comment by GeekTR** [comment]
@the-pig-of-jungle 我试了2.7.4不崩了

**Comment by GeekTR** [comment]
@the-pig-of-jungle 然后有了新的bug
Caused by: java.lang.ClassCastException: android.view.ViewRootImpl cannot be cast to android.view.ViewGroup
        at com.coder.zzq.smartshow.toast.BaseToastManager.showToast(BaseToastManager.java:108)
        at com.coder.zzq.smartshow.toast.PlainToastManager.showHelper(PlainToastManager.java:207)
        at com.coder.zzq.smartshow.toast.PlainToastManager.show(PlainToastManager.java:139)
        at com.coder.zzq.smartshow.toast.SmartToast.show(SmartToast.java:20)

**Comment by the-pig-of-jungle** [comment]
已修复

**Comment by JM0425** [comment]
> 已修复

怎么修复的？
